version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  app:
    build: .
    env_file:
      - .env.example
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:

